### ISSUE TITLE
error when running.

### ISSUE THREAD

**Issue by mgaulton** [Saberre/torrent-cleaner#2]
server6:/opt/utorrent/conf/webui/inprogress # cp /opt/utorrent/conf/resume.dat .
server6:/opt/utorrent/conf/webui/inprogress # python /opt/code/torrent-cleaner/torrent-cleaner.py -d /home/torrentflux/inprogress/
Traceback (most recent call last):
  File "/opt/code/torrent-cleaner/torrent-cleaner.py", line 43, in <module>
    main(args.path, args.dry)
  File "/opt/code/torrent-cleaner/torrent-cleaner.py", line 15, in main
    torrents = bencode.decode(data)
  File "/opt/code/torrent-cleaner/bencode.py", line 60, in decode
    raise SyntaxError("syntax error")
SyntaxError: syntax error

**Comment by Saberre** [comment]
What uTorrent version are you using?

**Comment by mgaulton** [comment]
linux utserver latest on opensuse 13.2

**Comment by Saberre** [comment]
I tested on uTorrent 2.2.1 (Windows), not on 3.x. Sorry for that. Changing bencode library to another can be a solution.

**Comment by mgaulton** [comment]
OK, i'll look at that. makes sense.
